### ISSUE TITLE
Menu not changing cookies and updating page

### ISSUE THREAD

**Issue by andpeterson** [andpeterson/HomestuckSimplifier#4]
Error in response to tabs.query: TypeError: Cannot read property 'id' of undefined
    at Object.callback (chrome-extension://lafgcjhdcmlfkikgpapndocbggihefme/popup.js:19:41)
    at window.onload (chrome-extension://lafgcjhdcmlfkikgpapndocbggihefme/popup.js:17:14)

**Comment by andpeterson** [comment]
Issue disappeared. Closing for now...
